
<header class="pageHeader">
	<nav class="pageHeaderProjectMenu">
		<button type="button" class="pageHeaderProjectMenu__switch" tabindex="0" title="Український фольклор за категоріями">&#x2630;</button>
		<div class="pageHeaderProjectMenu__items" tabindex="-1">
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Українські народні казки/" title="Українські народні казки">Казки</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Українські билини/" title="Українські народні билини">Билини</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Українські народні легенди/" title="Українські народні легенди">Легенди</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Українська міфологія/" title="Українські міфи">Міфи</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Українські народні оповідання/" title="Українські народні оповідання">Оповідання</a>
			<a class="pageHeaderProjectMenu__item" lang="ru" href="/Украинские народные легенды/" title="Украинские народные легенды">Легенды</a>
			<a class="pageHeaderProjectMenu__item" lang="ru" href="/Украинские народные сказки/" title="Украинские народные сказки">Сказки</a>
			<a class="pageHeaderProjectMenu__item" lang="en" href="/Ukrainian folk tales/" title="Ukrainian folk tales">Tales</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Словник діалектних та маловживаних слів/" title="Словник діалектних та маловживаних слів">Словник</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Аудіоказки/" title="Аудіоказки народні та авторські">Аудіоказки</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Український фольклор Книги/" title="Український фольклор">Книги</a>
		</div>
	</nav>
	<h1 class="pageHeaderProjectName" lang="uk">
		<a class="pageHeaderProjectName__link" href="/" title="Український фольклор — усна українська народна творчість — на головну сторінку проекту">Народна&nbsp;творчість</a>
	</h1>
	<nav class="pageHeaderAlphabetMenu">
		<button type="button" class="pageHeaderAlphabetMenu__switch" tabindex="0" title="Покажчик за абеткою">А—Я</button>
	</nav>
	<div class="pageHeader__shadow" tabindex="-1"></div>
	<div class="alphabetContent" tabindex="-1">
		<div class="alphabetContentTop">
			<div class="alphabetContentHeader"></div>
			<button type="button" class="alphabetContentClose"><svg class="alphabetContentCloseIcon" viewBox="0 0 13 13"><path d="M6.5 7.584 1.084 13 0 11.917 5.417 6.5 0 1.084 1.084 0 6.5 5.417 11.916 0 13 1.084 7.583 6.5 13 11.917 11.916 13z"/></svg></button>
		</div>
		<div class="alphabetContentItems" tabindex="0"></div>
	</div>
</header>
