
<header class="pageHeader">
	<nav class="pageHeaderProjectMenu">
		<div class="pageHeaderProjectMenu__switch" tabindex=0 role="button" title="Український фольклор за категоріями"><svg class="pageHeaderProjectMenu__switchIcon" aria-label="Меню Український фольклор за категоріями" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"></path></svg></div>
		<div class="pageHeaderProjectMenu__items">
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Українські народні казки/" title="Українські народні казки">Казки</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Українські билини/" title="Українські народні билини">Билини</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Українські народні легенди/" title="Українські народні легенди">Легенди</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Українська міфологія/" title="Українські міфи">Міфи</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Українські народні оповідання/" title="Українські народні оповідання">Оповідання</a>
			<a class="pageHeaderProjectMenu__item" lang="ru" href="/Украинские народные легенды/" title="Украинские народные легенды">Легенды</a>
			<a class="pageHeaderProjectMenu__item" lang="ru" href="/Украинские народные сказки/" title="Украинские народные сказки">Сказки</a>
			<a class="pageHeaderProjectMenu__item" lang="en" href="/Ukrainian folk tales/" title="Ukrainian folk tales">Tales</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Словник діалектних та маловживаних слів/" title="Словник діалектних та маловживаних слів">Словник</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Аудіоказки/" title="Аудіоказки народні та авторські">Аудіоказки</a>
			<a class="pageHeaderProjectMenu__item" lang="uk" href="/Український фольклор Книги/" title="Український фольклор">Книги</a>
		</div>
	</nav>
	<h1 class="pageHeaderProjectName" lang="uk">
		<a class="pageHeaderProjectName__link" href="/" title="Український фольклор — усна українська народна творчість — на головну сторінку проекту">Народна&nbsp;творчість</a>
	</h1>
	<nav class="pageHeaderAlphabetMenu">
		<div class="pageHeaderAlphabetMenu__switch" tabindex=0 role="button" title="Покажчик творів українського фольклору за абеткою">А—Я</div>
	</nav>
	<div class="pageHeader__shadow" tabindex=-1></div>
	<div class="alphabetContent" tabindex=-1></div>
</header>
