	<!--#include virtual="/-/inc/general__pageHead.inc" -->

	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			"itemListElement": [
				{
					"@type": "ListItem",
					"position": 1,
					"item": "https://proridne.org",
					"name": "Українська народна творчість"
				},
				{
					"@type": "ListItem",
					"position": 2,
					"item": "https://proridne.org/Український фольклор Книги/",
					"name": "Український фольклор в книгах"
				},
				{
					"@type": "ListItem",
					"position": 3,
					"item": "https://proridne.org/Український фольклор Книги/Іван Березовський ☼ Казки про тварин/",
					"name": "Іван Березовський ☼ Казки про тварин"
				}
			]
		}
	</script>

</head>

<body data-page-type="Книга Іван Березовський ☼ Казки про тварин">
	<!--#include virtual="/-/inc/general__body_header.inc" -->
	<main>
		<div class="linkToParent"><a href="/Український фольклор Книги/" title="Український фольклор в книгах">Книги</a></div>
