	<!--#include virtual="/-/inc/general__pageHead.inc" -->

	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			"itemListElement": [
				{
					"@type": "ListItem",
					"position": 1,
					"item": "https://proridne.org",
					"name": "Українська народна творчість"
				},
				{
					"@type": "ListItem",
					"position": 2,
					"item": "https://proridne.org/Ukrainian folk tales/",
					"name": "Ukrainian folk tales"
				}
			]
		}
	</script>

</head>

<body data-page-type="Ukrainian tale">
	<!--#include virtual="/-/inc/general__body_header.inc" -->
	<main>
		<div class="linkToParent"><a href="/Ukrainian folk tales/" title="Folk Tales of Ukraine">Ukrainian folk tales</a></div>
