	<!--#include virtual="/-/inc/general__pageHead.inc" -->

	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			"itemListElement": [
				{
					"@type": "ListItem",
					"position": 1,
					"item": "https://proridne.org",
					"name": "Українська народна творчість"
				},
				{
					"@type": "ListItem",
					"position": 2,
					"item": "https://proridne.org/Українська міфологія/",
					"name": "Українська міфологія"
				}
			]
		}
	</script>

</head>

<body data-page-type="Український міф">
	<!--#include virtual="/-/inc/general__body_header.inc" -->
	<main tabindex="-1">
	<!--#include virtual="/-/inc/myInfo.inc" -->
		<div class="linkToParent"><a href="/Українська міфологія/" title="Міфи України">Українська міфологія</a></div>
