	<!--#include virtual="/-/inc/general__pageHead.inc" -->

	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			"itemListElement": [
				{
					"@type": "ListItem",
					"position": 1,
					"item": "https://proridne.org",
					"name": "Українська народна творчість"
				},
				{
					"@type": "ListItem",
					"position": 2,
					"item": "https://proridne.org/Українські народні оповідання/",
					"name": "Українські народні оповідання"
				}
			]
		}
	</script>

</head>

<body data-page-type="Українське оповідання">
	<!--#include virtual="/-/inc/general__body_header.inc" -->
	<main>
		<div class="linkToParent"><a href="/Українські народні оповідання/" title="Оповідання України">Українські оповідання</a></div>
