	<!--#include virtual="/-/inc/general__pageHead.inc" -->

	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			"itemListElement": [
				{
					"@type": "ListItem",
					"position": 1,
					"item": "https://proridne.org",
					"name": "Українська народна творчість"
				},
				{
					"@type": "ListItem",
					"position": 2,
					"item": "https://proridne.org/Украинские народные сказки/",
					"name": "Украинские народные сказки"
				}
			]
		}
	</script>

</head>

<body data-page-type="Украинская сказка">
	<!--#include virtual="/-/inc/general__body_header.inc" -->
	<main tabindex="-1">
	<!--#include virtual="/-/inc/myInfo.inc" -->
		<div class="linkToParent"><a href="/Украинские народные сказки/" title="Сказки Украины">Украинские народные сказки</a></div>
