	<!--#include virtual="/-/inc/general__pageHead.inc" -->

	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			"itemListElement": [
				{
					"@type": "ListItem",
					"position": 1,
					"item": "https://proridne.org",
					"name": "Українська народна творчість"
				},
				{
					"@type": "ListItem",
					"position": 2,
					"item": "https://proridne.org/Український фольклор Книги/",
					"name": "Український фольклор в книгах"
				}
			]
		}
	</script>

</head>

<body data-page-type="Книга Микола Зінчук «Чарівні казки» Казка">
	<!--#include virtual="/-/inc/general__body_header.inc" -->
	<main>
		<div class="linkToParent"><a href="/Український фольклор Книги/Микола Зінчук ☼ Чарівні казки/" title="Микола Зінчук «Чарівні казки»">Чарівні казки</a></div>
