	<!--#include virtual="/-/inc/general__pageHead.inc" -->

	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			"itemListElement": [
				{
					"@type": "ListItem",
					"position": 1,
					"item": "https://proridne.org",
					"name": "Українська народна творчість"
				}
			]
		}
	</script>

</head>

<body data-page-type="Головна">
	<!--#include virtual="/-/inc/general__body_header.inc" -->
	<main>
