	<!--#include virtual="/-/inc/general__pageHead.inc" -->

	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			"itemListElement": [
				{
					"@type": "ListItem",
					"position": 1,
					"item": "https://proridne.org",
					"name": "Українська народна творчість"
				},
				{
					"@type": "ListItem",
					"position": 2,
					"item": "https://proridne.org/Український фольклор Книги/",
					"name": "Український фольклор в книгах"
				},
				{
					"@type": "ListItem",
					"position": 3,
					"item": "https://proridne.org/Український фольклор Книги/Іван Котляревський ☼ Енеїда/",
					"name": "Іван Котляревський ☼ Енеїда"
				}
			]
		}
	</script>

</head>

<body data-page-type="Книга Іван Котляревський «Енеїда» Розділ">
	<!--#include virtual="/-/inc/general__body_header.inc" -->
	<main tabindex="-1">
	<!--#include virtual="/-/inc/myInfo.inc" -->
		<div class="linkToParent"><a href="/Український фольклор Книги/Іван Котляревський ☼ Енеїда/" title="Іван Котляревський «Енеїда»">Іван Котляревський ☼ Енеїда</a></div>
