	<!--#include virtual="/-/inc/general__pageHead.inc" -->

	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			"itemListElement": [
				{
					"@type": "ListItem",
					"position": 1,
					"item": "https://proridne.org",
					"name": "Українська народна творчість"
				},
				{
					"@type": "ListItem",
					"position": 2,
					"item": "https://proridne.org/Украинские народные легенды/",
					"name": "Украинские народные легенды"
				}
			]
		}
	</script>

</head>

<body data-page-type="Украинская легенда">
	<!--#include virtual="/-/inc/general__body_header.inc" -->
	<main tabindex="-1">
	<!--#include virtual="/-/inc/myInfo.inc" -->
		<div class="linkToParent"><a href="/Украинские народные легенды/" title="Легенды Украины">Украинские легенды</a></div>
