	<!--#include virtual="/-/inc/general__pageHead.inc" -->

	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			"itemListElement": [
				{
					"@type": "ListItem",
					"position": 1,
					"item": "https://proridne.org",
					"name": "Українська народна творчість"
				},
				{
					"@type": "ListItem",
					"position": 2,
					"item": "https://proridne.org/Український фольклор Книги/",
					"name": "Український фольклор в книгах"
				},
				{
					"@type": "ListItem",
					"position": 3,
					"item": "https://proridne.org/Український фольклор Книги/Ірина Кімакович ☼ Фольклорний анекдот як жанр/",
					"name": "Ірина Кімакович ☼ Фольклорний анекдот як жанр"
				}
			]
		}
	</script>

</head>

<body data-page-type="Книга Ірина Кімакович «Фольклорний анекдот як жанр» Розділ">
	<!--#include virtual="/-/inc/general__body_header.inc" -->
	<main tabindex="-1">
	<!--#include virtual="/-/inc/myInfo.inc" -->
		<div class="linkToParent"><a href="/Український фольклор Книги/Ірина Кімакович ☼ Фольклорний анекдот як жанр/" title="Ірина Кімакович «Фольклорний анекдот як жанр»">Ірина Кімакович ☼ Фольклорний анекдот як жанр</a></div>
