	<!--#include virtual="/-/inc/general__pageHead.inc" -->

	<script type="application/ld+json">
		{
			"@context": "https://schema.org",
			"@type": "BreadcrumbList",
			"itemListElement": [
				{
					"@type": "ListItem",
					"position": 1,
					"item": "https://proridne.org",
					"name": "Українська народна творчість"
				},
				{
					"@type": "ListItem",
					"position": 2,
					"item": "https://proridne.org/Український фольклор Книги/",
					"name": "Український фольклор в книгах"
				},
				{
					"@type": "ListItem",
					"position": 3,
					"item": "https://proridne.org/Український фольклор Книги/Валерій Войтович ☼ Молитва до Дажбога/",
					"name": "Валерій Войтович ☼ Молитва до Дажбога"
				}
			]
		}
	</script>

</head>

<body data-page-type="Книга Валерій Войтович «Молитва до Дажбога» Розділ">
	<!--#include virtual="/-/inc/general__body_header.inc" -->
	<main>
		<div class="linkToParent"><a href="/Український фольклор Книги/Валерій Войтович ☼ Молитва до Дажбога/" title="Валерій Войтович «Молитва до Дажбога»">Валерій Войтович ☼ Молитва до Дажбога</a></div>
